### ISSUE TITLE
Construction of PrimaryCaps

### ISSUE THREAD

**Issue by manuelsh** [XifengGuo/CapsNet-Pytorch#2]
I believe this line:

https://github.com/XifengGuo/CapsNet-Pytorch/blob/8a5a3572d91eb9479425168d3d565eb02e78be46/capsulelayers.py#L104

is not making the capsules in the right way. In theory if we do:

`outputs = self.conv2d(x)
outputs_2 = outputs.view(x.size(0), -1, self.dim_caps)`

then `outputs[0,0:8,0,0]` should be equal to `outputs_2[0,0,0:8]`

and if you apply the view in that way this may not be guaranteed.

**Comment by manuelsh** [comment]
I believe you should permute the dimensions to be [batch_size, 6, 6, 256] before doing the view.

See for example the original implementation of the authors:

https://github.com/Sarasra/models/blob/984fbc754943c849c55a57923f4223099a1ff88c/research/capsules/models/capsule_model.py#L68

**Comment by XifengGuo** [comment]
@manuelsh Yes, you are totally right. Thanks.

**Comment by manuelsh** [comment]
What are your results if you do that? Our experience so far seems that with the correct view the results are actually worse. (!)

Btw, we are using cosine annealing as learning rate decay and works better than the exponential one.

**Comment by BearockXY** [comment]
I use python 2.7 and cuda 9.1 to run the code. I met some warming and error.

capsulenet.py:165: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  training_loss += loss.data[0] * x.size(0)  # record the batch loss
capsulenet.py:121: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  x, y = Variable(x.cuda(), volatile=True), Variable(y.cuda())
capsulenet.py:123: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  test_loss += caps_loss(y, y_pred, x, x_recon, args.lam_recon).data[0] * x.size(0)  # sum up batch loss
Traceback (most recent call last):
  File "capsulenet.py", line 255, in <module>
    train(model, train_loader, test_loader, args)
  File "capsulenet.py", line 169, in train
    val_loss, val_acc = test(model, test_loader, args)
  File "capsulenet.py", line 129, in test
    return test_loss, correct / len(test_loader.dataset)
RuntimeError: value cannot be converted to type uint8_t without overflow: 10000

Do you have any idea how to solve it?
